# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  AZURE_WEBAPP_NAME: devopsdemo007    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run:  dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2.3.1
      with:
        name: webapp
        path: website/**
        if-no-files-found: warn
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        name: webapp
        path: webapp
    - name: Deploy web app
      uses: azure/webapps-deploy@v2
      with:
        app-name: GitHubApp-@lab.LabInstance.Id
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: webapp


